hardcodedNameSpace: cert-manager
showVerionsTab: false
showEnvVarsTab: true
useRawYaml: true
allowAutoApplyLimits: false
name: cert-manager
title: cert-manager
logo: null
tags:
  - certmanager
description: cert-manager
oneDeploymentPerCluster: true
notAllowRemoveNamespace: false
